### ISSUE TITLE
Use of deprecated functions

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk-rdt#27]
There is some code in nxdk-rdt which uses `XSleep` or `XGetTickCount`.

nxdk provides the proper winapi implementations which should be used instead.

However, some of that code appears to be in gfx.c which is likely unused, so the deprecated code can probably be removed (although we still have to initialize the GPU because some scripts expect this).

**Comment by thrimbor** [comment]
Should be fixed as of https://github.com/XboxDev/nxdk-rdt/pull/28
