### ISSUE TITLE
Support calling arbitrary functions (including kernel functions)

### ISSUE THREAD

**Issue by mborgerson** [XboxDev/nxdk-rdt#6]
We should be able to call any kernel function remotely. Even better, call *anything* remotely. That is, if we write some bytes into memory, we should be able to jump into that memory. For this we will need to be able to pass the arguments correctly before making the jump. Then return the function return value (probably just all CPU regs) back to the client.

**Comment by JayFoxRox** [comment]
For your information: https://github.com/JayFoxRox/nxdk-rdt/pull/4
This branch has a partial implementation of this (just needs some polish).
